version: '3.8'

services:
  backend:
    build:
      context: ./path-to-your-backend
      dockerfile: Dockerfile
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./path-to-your-backend:/usr/src/app
    environment:
      - DJANGO_SETTINGS_MODULE=your_project.settings
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./path-to-your-frontend
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "80:80"
